var footer =
'<footer class="t-center">'
+'	<div class="wrap-footer">'
+'		<div class="zerogrid">'
+'			<div class="row">'
+'				<span class="phone">联系电话: 13035184979</span>'
+'				<br>'
+'				<span class="phone">地址: 应城市东马坊枣林路103号</span>'
+'				<br>'
+'				<span class="phone">地址: 应城市东马坊化工大道41号</span>'
+'			</div>'
+'		</div>'
+'	</div>'
+'	<div class="bottom-footer">'
+'		<div class="zerogrid">'
+'			<div class="row">'
+'				<div class="copy-right">'
+'					<p>Copyright @ 三平金属结构制作 - More Templates <a href="https://spjsjg.dns.army/" title="三平金属结构制作">三平金属结构制作</a></p>'
+'				</div>'
+'			</div>'
+'		</div>'
+'	</div>'
'</footer>'

document.write(footer)
